import { useEffect, useState } from "react";
import { BarChart3, Download, RefreshCw } from "lucide-react";
import { mangaErpApi } from "../../shared/services/mangaErpService";
import type { BoardPerformanceReportDto, BoardReportDto } from "../../shared/types/mangaErp";
import { useToast } from "../../shared/components/toastContext";

export default function ReportsPage() {
  const toast = useToast(); const [report, setReport] = useState<BoardReportDto | null>(null); const [performance, setPerformance] = useState<BoardPerformanceReportDto | null>(null); const [loading, setLoading] = useState(true);
  const load = async () => { setLoading(true); try { const [summary, detail] = await Promise.all([mangaErpApi.getBoardReports(), mangaErpApi.getBoardPerformanceReports()]); setReport(summary); setPerformance(detail); } catch (error) { toast.error("Could not load Board reports", error instanceof Error ? error.message : "Unknown error"); } finally { setLoading(false); } };
  // Initial backend load only.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(() => { const timer = window.setTimeout(() => { void load(); }, 0); return () => window.clearTimeout(timer); }, []);
  const exportCsv = async () => { try { const blob = await mangaErpApi.exportBoardReports(); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = "board-reports.csv"; link.click(); URL.revokeObjectURL(url); } catch (error) { toast.error("Could not export reports", error instanceof Error ? error.message : "Unknown error"); } };
  const cards = [["In review", report?.submissions.totalInReview ?? performance?.totalPending ?? 0], ["Conflicts", report?.submissions.conflictEscalated ?? performance?.totalConflict ?? 0], ["Cancellation requests", report?.cancellations.pendingApproval ?? 0], ["Avg. processing", `${performance?.avgProcessingHours ?? 0}h`]];
  return <div className="space-y-6"><header className="flex items-end justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-[.28em] text-fuchsia-200">Editorial Board</p><h1 className="mt-2 text-3xl font-black text-white">Reports</h1></div><div className="flex gap-2"><button type="button" onClick={() => void exportCsv()} className="inline-flex items-center gap-2 rounded-lg border border-fuchsia-300/30 px-3 py-2 text-sm font-semibold text-fuchsia-100"><Download size={16}/>Export CSV</button><button type="button" title="Refresh reports" onClick={() => void load()} className="icon-button"><RefreshCw size={17}/></button></div></header><section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{cards.map(([label, value]) => <div key={String(label)} className="border border-white/10 bg-slate-900 p-4"><p className="text-xs uppercase tracking-[.16em] text-slate-400">{label}</p><p className="mt-2 text-2xl font-black text-white">{loading ? "..." : value}</p></div>)}</section><section className="grid gap-5 lg:grid-cols-2"><article className="border border-white/10 bg-slate-900 p-5"><h2 className="flex items-center gap-2 text-lg font-bold text-white"><BarChart3 size={18} className="text-fuchsia-200"/>Decision rates</h2><div className="mt-5 space-y-4">{[["Approve", performance?.approveRate], ["Revision", performance?.revisionRate], ["Reject", performance?.rejectRate]].map(([label, value]) => <div key={String(label)}><div className="flex justify-between text-sm"><span className="text-slate-300">{label}</span><span className="text-white">{value ?? 0}%</span></div><div className="mt-2 h-2 bg-slate-800"><div className="h-full bg-fuchsia-400" style={{ width: `${Math.min(Number(value ?? 0), 100)}%` }}/></div></div>)}</div></article><article className="border border-white/10 bg-slate-900 p-5"><h2 className="text-lg font-bold text-white">Vote distribution</h2><div className="mt-4 space-y-3">{performance?.voteBreakdown.map((item) => <div key={item.voteType} className="flex justify-between border-b border-white/10 pb-3 text-sm"><span className="text-slate-300">{item.voteType}</span><span className="font-bold text-white">{item.count}</span></div>)}{!performance?.voteBreakdown.length ? <p className="text-sm text-slate-500">No vote data yet.</p> : null}</div></article></section></div>;
}
