#!/bin/sh
set -eu

cat > /usr/share/nginx/html/env.js <<EOF
window.__APP_CONFIG__ = {
  VITE_API_BASE_URL: "${VITE_API_BASE_URL:-}",
  VITE_IDENTITY_API_BASE_URL: "${VITE_IDENTITY_API_BASE_URL:-}",
  VITE_SUBMISSION_API_BASE_URL: "${VITE_SUBMISSION_API_BASE_URL:-}",
  VITE_SERIES_API_BASE_URL: "${VITE_SERIES_API_BASE_URL:-}",
  VITE_CHAPTER_API_BASE_URL: "${VITE_CHAPTER_API_BASE_URL:-}",
  VITE_TASK_API_BASE_URL: "${VITE_TASK_API_BASE_URL:-}",
  VITE_QA_API_BASE_URL: "${VITE_QA_API_BASE_URL:-}",
  VITE_PUBLISHING_API_BASE_URL: "${VITE_PUBLISHING_API_BASE_URL:-}",
  VITE_RANKING_API_BASE_URL: "${VITE_RANKING_API_BASE_URL:-}"
};
EOF

exec "$@"
